blank_issues_enabled: false

contact_links:
  - name: General Discussion
    url: https://github.com/orgs/T-Craft-Platforms/discussions
    about: >
      For general questions, help, ideas, or discussions.
      Use issues only for concrete technical topics related to this repository.
